<section class="slide" id="<?= getSlideId(__FILE__) ?>">
    <div>
        <span class="chapter">Chapter 2</span>
        <h2>(Anti-)CSRF Token</h2>

        <ul class="small">
            <li>Any state changing operation requires a secure random token to prevent CSRF attacks</li>
            <li>Characteristics of a CSRF Token:
                <ul>
                    <li>Unique per user session</li>
                    <li>Large random value</li>
                    <li>Generated by a cryptographically secure random number generator</li>
                </ul>
            </li>
            <li>The CSRF token is added as a hidden field for forms or within the URL if the state changing operation occurs via a GET request</li>
            <li>The server rejects the requested action if the CSRF token fails validation</li>
        </ul>
    </div>
</section>